name: Mobile + Release
on: workflow_dispatch
jobs:
  Android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp --quiet
          haxelib git lime https://github.com/mcagabe19-stuff/lime --quiet
          haxelib install openfl 9.3.3 --quiet
          haxelib install flixel 5.6.1 --quiet
          haxelib install flixel-addons 3.2.2 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install SScript 19.0.618 --quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 768740a56b26aa0c072720e0d1236b94afe68e3e --quiet
          haxelib git linc_luajit https://github.com/mcagabe19-stuff/linc_luajit-legacy 923a8262a7a8dcd166264dcf22cb7395a11fba65 --quiet --skip-dependencies
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc 3538a1c2bb07b04208cd014220207f8173acdb21 --quiet --skip-dependencies
          haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc 70e7f5f3e76d526ac6fb8f0e6665efe7dfda589d --quiet --skip-dependencies
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis d5361037efa3a02c4ab20b5bd14ca11e7d00f519 --quiet --skip-dependencies
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio.git cbf91e2180fd2e374924fe74844086aab7891666 --quiet
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools 727693f0a76c6e396df675bb0ed95d7639a4db01 --quiet --skip-dependencies

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build android -D officialBuild -final

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
  iOS:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp --quiet
          haxelib git lime https://github.com/mcagabe19-stuff/lime --quiet
          haxelib install openfl 9.3.3 --quiet
          haxelib install flixel 5.6.1 --quiet
          haxelib install flixel-addons 3.2.2 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install SScript 19.0.618 --quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 768740a56b26aa0c072720e0d1236b94afe68e3e --quiet
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit 1906c4a96f6bb6df66562b3f24c62f4c5bba14a7 --quiet
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc 3538a1c2bb07b04208cd014220207f8173acdb21 --quiet --skip-dependencies
          haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc 70e7f5f3e76d526ac6fb8f0e6665efe7dfda589d --quiet --skip-dependencies
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis d5361037efa3a02c4ab20b5bd14ca11e7d00f519 --quiet --skip-dependencies
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio.git cbf91e2180fd2e374924fe74844086aab7891666 --quiet

      - name: Compile
        run: haxelib run lime build ios -nosign -D officialBuild -final

      - name: Make Ipa
        run: |
          cd export/release/ios/build/*-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r PsychEngine.ipa Payload

      - name: Make Zip For Release
        run: |
           cd export/release/ios/build/*-iphoneos
           zip PsychEngine-iOS.zip PsychEngine.ipa

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.zip
          if-no-files-found: error
  Releaser:
    needs: [Android, iOS]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild
           path: /home/runner

      - name: Move Android File
        run: mv /home/runner/PsychEngine-release.apk /home/runner/PsychEngine-Android.apk

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
           name: iOSBuild
           path: /home/runner

      - name: Publish The Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "1.0-prerelease"
          title: "1.0"
          files: |
            /home/runner/*.apk
            /home/runner/*.zip
